@startuml database
  entity Activity {
    * id
    --
    * title
    * image_id
  }

  entity Seance {
    * id
    --
    * num_day
    * start_hour
    * end_hour
    * custom_date: bool
    nb_max
  }

  entity Booking {
    * id
    --
    * lastname
    * firstname
    * amount
    * paid
    * phone
    * birthdate
    email
    * date
  }

  entity Date {
    * id
    --
    * type : ["cancel", "custom"]
    * date
  }

  entity Charity {
    * id
    --
    * name
    * contact
    address
    city
    country
  }

  Activity ||..o{ Seance
  Seance ||..o{ Booking
  Seance ||..o{ Date
  Charity ||..o{ Booking
@enduml