@startuml database
  entity Activity {
    * code
    --
    * label
  }

  entity Session {
    * id
    --
    * num_day
    * start_hour
    * end_hour
    * isWeekly: bool
    nb_max
    * activity_id
  }

  entity Booking {
    * id
    --
    * lastname
    * firstname
    * amount
    * is_paid
    * phone
    * birthdate
    email
    * date
    * charity_id
    * session_id
  }

  entity Date {
    * id
    --
    * type : ["canceled", "custom"]
    * date
    * session_id
  }

  entity Charity {
    * name
    --
    * contact
    address
    city
    zip_code
    country
  }


  Activity::code <-up- Session::activity_id
  Session::id <-right- Booking::session_id
  Session::id <-right- Date::session_id
  Charity::name <-up- Booking::charity_id
@enduml